DROP TABLE HOLDS;
DROP TABLE MANAGES;
DROP TABLE TAKES_OUT;
DROP TABLE DEPENDENT;
DROP TABLE CUSTOMER;
DROP TABLE LOAN;
DROP TABLE OVERDRAFT;
DROP TABLE TRANSACTION;
DROP TABLE ASSETS;
DROP TABLE ACCOUNT;
DELETE FROM EMPLOYEE;
DELETE FROM BRANCH;
ALTER TABLE EMPLOYEE DROP CONSTRAINT Branch;
DROP TABLE BRANCH;
DROP TABLE EMPLOYEE;

CREATE TABLE EMPLOYEE(
    ssn CHAR(9) NOT NULL,
    Fname VARCHAR(15) NOT NULL,
    Minit CHAR(1),
    Lname VARCHAR(20) NOT NULL,
    managerSSN CHAR(9),
    assistantManagerSSN CHAR(9), 
    branchID VARCHAR(5), 
    startDate DATE DEFAULT CURRENT_DATE NOT NULL,
    phoneNo CHAR(10),
    sex CHAR(1),
    dob DATE,
    salary DECIMAL(15,2),
    street VARCHAR(20),
    state CHAR(2),
    city VARCHAR(1250),
    zipCode CHAR(5),
    PRIMARY KEY (ssn)
);

CREATE TABLE BRANCH (
    branchID VARCHAR(5) NOT NULL,
    street VARCHAR(20) NOT NULL,
    state CHAR(2) NOT NULL,
    city VARCHAR(25) NOT NULL,
    zipCode CHAR(5) NOT NULL,
    managerSSN CHAR(9),
    assistantManagerSSN CHAR(9),
    phoneNo CHAR(10),
    PRIMARY KEY (branchID),
    FOREIGN KEY (managerSSN) REFERENCES EMPLOYEE(ssn) ON DELETE SET NULL,
    FOREIGN KEY (assistantManagerSSN) REFERENCES EMPLOYEE(ssn) ON DELETE SET NULL
);


CREATE TABLE ASSETS (
    branchID VARCHAR(5) NOT NULL,
    assetName VARCHAR(50) NOT NULL,
    PRIMARY KEY (branchID, assetName),
    FOREIGN KEY (branchID) REFERENCES BRANCH(branchID) ON DELETE CASCADE);

CREATE TABLE LOAN(
loanNo CHAR(5) NOT NULL,
amount DECIMAL(15, 2) NOT NULL,
branchID VARCHAR(5) NOT NULL,
repaymentAmount DECIMAL(15, 2) NOT NULL,
PRIMARY KEY(loanNo),
FOREIGN KEY(branchID) REFERENCES BRANCH(branchID) ON DELETE CASCADE);

CREATE TABLE DEPENDENT(
dependentName VARCHAR(15) NOT NULL,
essn CHAR(9) NOT NULL,
sex CHAR(1),
dob DATE,
PRIMARY KEY (dependentName, essn),
FOREIGN KEY (essn) REFERENCES EMPLOYEE (ssn) ON DELETE CASCADE);

CREATE TABLE CUSTOMER(
ssn CHAR(9) NOT NULL,
Fname VARCHAR(15) NOT NULL,
Minit CHAR(1),
Lname VARCHAR(20) NOT NULL,
aptNo INT,
street VARCHAR(20) NOT NULL,
state CHAR(2) NOT NULL,
city VARCHAR(25) NOT NULL,
zip CHAR(5) NOT NULL,
Essn CHAR(9) NOT NULL, 
branchID VARCHAR(5),
PRIMARY KEY (ssn),
FOREIGN KEY (Essn) REFERENCES EMPLOYEE (ssn),
FOREIGN KEY (branchID) REFERENCES BRANCH(branchID) ON DELETE SET NULL);

CREATE TABLE ACCOUNT(
accountNo CHAR(5) NOT NULL,
balance DECIMAL(15, 2) DEFAULT 0 NOT NULL ,
Type VARCHAR(25) NOT NULL,
fixedInterestRate DECIMAL(5, 4),
variableInterestRate DECIMAL(5, 4),
accessDate DATE DEFAULT CURRENT_DATE  NOT NULL ,
PRIMARY KEY (accountNo));

CREATE TABLE MANAGES(
customerSSN CHAR(9) NOT NULL,
accountNo CHAR(5) NOT NULL,
PRIMARY KEY (customerSSN, accountNo),
FOREIGN KEY (customerSSN) REFERENCES CUSTOMER (ssn) ON DELETE CASCADE,
FOREIGN KEY (accountNo) REFERENCES ACCOUNT (accountNo) ON DELETE CASCADE);

CREATE TABLE TRANSACTION(
accountNo CHAR(5) NOT NULL,
code CHAR(5) NOT NULL,
name CHAR(2) NOT NULL,
amount DECIMAL(15, 2) NOT NULL,
transaction_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
transaction_date DATE DEFAULT CURRENT_DATE NOT NULL, 
charge NUMBER(1) NOT NULL, 
PRIMARY KEY (code),
FOREIGN KEY (accountNo) REFERENCES ACCOUNT(accountNo) ON DELETE CASCADE);

CREATE TABLE HOLDS(
accountNo CHAR(5) NOT NULL,
loanNo CHAR(5) NOT NULL,
PRIMARY KEY (accountNo, loanNo),
FOREIGN KEY (accountNo) REFERENCES ACCOUNT(accountNo) ON DELETE CASCADE,
FOREIGN KEY (loanNo) REFERENCES LOAN(loanNo) ON DELETE CASCADE);

CREATE TABLE OVERDRAFT(
accountNo CHAR(5) NOT NULL,
amount DECIMAL(15, 2) NOT NULL,
PRIMARY KEY (accountNo, amount),
FOREIGN KEY (accountNo) REFERENCES ACCOUNT(accountNo)ON DELETE CASCADE);

CREATE TABLE TAKES_OUT(
customerSSN CHAR(9) NOT NULL,
loanNo CHAR(5) NOT NULL,
PRIMARY KEY (customerSSN, loanNo),
FOREIGN KEY (customerSSN) REFERENCES CUSTOMER(ssn) ON DELETE CASCADE,
FOREIGN KEY (loanNo) REFERENCES LOAN(loanNo) ON DELETE CASCADE);

ALTER TABLE EMPLOYEE ADD CONSTRAINT Emp_Mgr FOREIGN KEY (managerSSN) REFERENCES EMPLOYEE(Ssn)
ON DELETE SET NULL;
ALTER TABLE EMPLOYEE ADD CONSTRAINT Emp_Asst_Mgr FOREIGN KEY (assistantManagerSSN) REFERENCES EMPLOYEE(Ssn)
ON DELETE SET NULL;
ALTER TABLE EMPLOYEE ADD CONSTRAINT Branch FOREIGN KEY (branchID) REFERENCES BRANCH(branchID)
ON DELETE CASCADE;


